name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name BreezeShane
          git config user.email 72027962+BreezeShane@users.noreply.github.com
          git add -A .
          if git commit -m "Generated 3D Profile."; then
            git push
          fi
