name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Timeline
          SHOW_LOC_CHART: True
          # Language
          SHOW_LANGUAGE: True
          # Operate System
          SHOW_OS: True
          # Projects
          SHOW_PROJECTS: True
          # Editors
          SHOW_EDITORS: True
          # The number of repository in different language and frameworks
          SHOW_LANGUAGE_PER_REPO: True
